export const productList = [
  {
    title: "Mug",
    text: "Best mug in your tea's life",
    img: "img/catalog/mug.webp",
    price: 10,
    id: 0,
  },
  {
    title: "Cap",
    text: "Best cap in your head's life",
    img: "img/catalog/cap.webp",
    price: 20,
    id: 1,
  },
  {
    title: "Backpack",
    text: "Best backpack in your back's life",
    img: "img/catalog/backpack.jpg",
    price: 30,
    id: 2,
  },
  {
    title: "Phone case",
    text: "Best case in your phone's life",
    img: "img/catalog/case.webp",
    price: 15,
    id: 3,
  },
  {
    title: "Black T-Shirt",
    text: "Basic t-shirt",
    img: "img/catalog/blackTshirt.jpg",
    price: 10,
    id: 4,
  },
  {
    title: "White T-Shirt",
    text: "Basic t-shirt",
    img: "img/catalog/whiteTshirt.jpg",
    price: 20,
    id: 5,
  },
  {
    title: "Black Hoodie",
    text: "Basic hoodie",
    img: "img/catalog/blackHoodie.jpg",
    price: 30,
    id: 6,
  },
  {
    title: "Phone case2",
    text: "Best case in your phone's life",
    img: "img/catalog/case.webp",
    price: 15,
    id: 7,
  },
  {
    title: "Mug2",
    text: "Best mug in your tea's life",
    img: "img/catalog/mug.webp",
    price: 10,
    id: 8,
  },
  {
    title: "Cap2",
    text: "Best cap in your head's life",
    img: "img/catalog/cap.webp",
    price: 20,
    id: 9,
  },
  {
    title: "Backpack2",
    text: "Best backpack in your back's life",
    img: "img/catalog/backpack.jpg",
    price: 30,
    id: 10,
  },
  {
    title: "Phone case2",
    text: "Best case in your phone's life",
    img: "img/catalog/case.webp",
    price: 15,
    id: 11,
  },
];
